### PR TITLE
F15e development (still work in progress)

### PR DESCRIPTION
**Pull request by blueberrypi-studio**
## Good news Eagle fans

DCS The Way is being developed for the F15E

The majority of the code is done, just waiting for the release to get a few of the final pieces, but the beta release should be available a few days after the F15E releases.

Target points are currently a work in progress, if this gets completed before release it will be in the beta, otherwise, it will be added as an update down the road

Enjoy

Any questions comment on this pull request

-Hayds_93

### CODE REVIEW

**Comment by aronCiucu** [comment]
Wow, good work there!

**Comment by blueberrypi-studio** [comment]
> Wow, good work there!

Thanks 🙏

Took a while to figure out, but once I got there it was easy. It's a nice framework. I'm currently trying to add a checkbox to the update waypoint part. I think there's a piece of code I'm missing because it doesn't update. But I'll work on it a bit more today

It currently has a warning like the f18 about being configured correctly. But theoretically that can be removed, but I need to test with the jet first. (the eagle doesn't have a dobber switch like the viper to easily return to a fixed point)

**Comment by blueberrypi-studio** [comment]
Removed the long switch case for typing in ICP in the viper (as a trial for my eagle code). Replaced with a loop and an array of codes at the top of the file.

```js
        //type long
        for (let i = 0; i < waypoint.long.length; i++) {
          // eslint-disable-next-line default-case
          for (const char of waypoint.long.charAt(i)) {
            
            if (char !== ".") {
              payload.push({
                device: 17,
                code: f16cNumberCodes[char],
                delay: 10,
                activate: 1,
                addDepress: "true",
              });
            }
          }
        }
```

**Comment by blueberrypi-studio** [comment]
@aronCiucu Code is ready to go :-) up to you whether you want to merge ASAP or let more testing happen.

No major bugs with the strike eagle code have been found, and the one bug i did find has been patched, everything else should theoretically be isolated now.

For now anyone can download my release at https://github.com/blueberrypi-studio/DCSTheWay/releases/tag/V2.1.3

**Comment by aronCiucu** [comment]
Hi, thanks, I will be taking a look at the code, and also do some changes along the way, for a new release

**Comment by blueberrypi-studio** [comment]
I'll make sure all my latest changes are committed then

**Comment by blueberrypi-studio** [comment]
I also need to add a section to either the readme or your release with the FAQ, because there's some quirks. (Maybe copy paste the below into the release notes)

## DCS the way: F-15E FAQ

* The way uses the B route waypoints, so any preset mission waypoints are not overwritten by the way

* Due to how the F-15 handles waypoints, it will always start from point 1B (there is no "next waypoint button")

* You will need to select which seat you are in, even in VR unfortunately. (Fix WIP)

* route B waypoints (what the way uses) do not show up on A/G Radar. You can still slave the cursor with PB17. 

* target points are not currently supported, and you will need to make sure that there are no target points set in route B. (you can use them in the Jet, but the way will fail if it tries to edit a target point, so just reset it to a steerpoint)

* Target point and INS points are WIP, you can still set these manually after using the way by changing the numbers

## changelog

* Added F-15E support (Pilot/WSO)
* Added all IDF mods F-16s
* Added all Superbug F/A-18s (E/F/G)

**Pull request merged**
