### PR TITLE
Support for Mirage F1EE

### PR DESCRIPTION
**Pull request by martinengstrom**
Support for Mirage F1EE, Module picture was downloaded from Aerges facebook page.

Aerges may decide to change button codes in the future since the modules are still early access, but this works with the current open beta.

### CODE REVIEW

**Comment by blueberrypi-studio** [comment]
is this compatible with all versions of the F1? if they work the same it shouldn't be too hard to do (I don't have it, I'm just curious)

**Comment by martinengstrom** [comment]
> is this compatible with all versions of the F1? if they work the same it shouldn't be too hard to do (I don't have it, I'm just curious)

No. The F1EE is the only one with INS, the F1CE version can only navigate using TACAN/VOR so it doesnt support the concept of waypoints.

**Comment by aronCiucu** [comment]
Hello, can you confirm this is still working with the latest open beta? @martinengstrom

**Comment by blueberrypi-studio** [comment]
Hey @aronCiucu do you have an ETA on next patch? I have an idea to make my F-15E code better, but need a few days as I'm away

(Could theoretically test the F1 code and the F-15E changes too for ya)

**Comment by aronCiucu** [comment]
@blueberrypi-studio I was planning to publish a new release as soon as I could confirm the Mirage F1 to be working still

**Comment by martinengstrom** [comment]
> No rush, I've made merged this into the miragef1 branch and it should be good to go for testing

FYI I checked out the miragef1 branch and did a quick test with the current OB and it seems to work fine.

**Comment by aronCiucu** [comment]
Thanks!

**Pull request merged**
