### PR TITLE
Feature/uh60l

### PR DESCRIPTION
**Pull request by shearn89**
Adds in support for the free UH-60L mod, with a couple caveats:

- It assumes you are on WPT0 on the TGT/WPT screen, and always increments before adding points, retaining MIZ0 as home plate
- It will always decrement back to the original WPT when done
- It will overwrite without confirmation, starting from WPT 01, with whatever is in TheWay
- It will not return you to the page/mode you were in, so if you were in MGRS it stays in LAT/LONG after input, and if you were on e.g. PP view, it stays in TGT/WPT.

Otherwise, it works!

### CODE REVIEW

**Comment by shearn89** [comment]
Addresses #128

**Comment by shearn89** [comment]
Okay - tested with special characters `space` and `*` - both working in game. This is ready for merge.

**Comment by aronCiucu** [comment]
Hello, good work, one thing I would add is a confirmation dialog so that the user is informed about the conditions in which the waypoint transfer works (being in WPT0 on the TGT/WPT screen)

**Comment by shearn89** [comment]
Hey, thanks - I can take a look at adding that in, my front end skills are rusty though! You don't /have/ to be on 0, it will increment from wherever you currently are and return there. But if you're not on 0, and have labelled your waypoints "waypoint 1" etc then the numbers won't match...

I'll take a look at a prompt tomorrow, time permitting.

**Comment by aronCiucu** [comment]
Oh I see, I thought it was required or the script won't work. I could also do this as well, don't worry about it

**Comment by blueberrypi-studio** [comment]
If you need a prompt, just cross reference the hornets code (just search for it) and you will see a menu, just copy that and it will work, no need for any fancy front end

@shearn89

**Comment by shearn89** [comment]
@aronCiucu no, it's not required, but I'll try to add some kind of documentation on it somewhere! The important bit is probably that it overwrites whatever is in the system. So you can start from any selected point but if you had 10 waypoints, then went to number 5 and loaded 10 from TheWay you'd end up with 5 old (1-5 in the system) and 10 new...

@blueberrypi-studio cool - I'd spotted the 'askUserAboutSeat.js' with an alert in it for the Hornet, so will use that as a template!

**Comment by blueberrypi-studio** [comment]
If it doesn't need one to operate successfully, don't put one in, unless @aronCiucu can add his user preferences code in to make it only show once. 

The hornets code breaks if your are in the wrong mode, so it needs the confirm menu

But again it's theoretically possible to make the warning popup once, which is perfect

**Comment by shearn89** [comment]
Cool - I've added an alert that can be hidden permanently, same as the Hornet. Hopefully that provides some context for the user!

**Comment by shearn89** [comment]
Hi @aronCiucu - is there any other changes you'd like on this? I'd be keen to get it merged.

**Comment by aronCiucu** [comment]
Hello, it's looking good so far, I will merge it as soon as I can

**Pull request merged**
