### PR TITLE
Support for Multiple Monitors

### PR DESCRIPTION
**Pull request by BlueFinBima**
Hi Aron, great job with this.  
This PR relates to the problem reported in (#3) about multiple monitors.  While the correct approach would be to read the options.lua and then the active monitorsetup lua file to work out where the F10 map will appear, life is too short, so I opted for command line options to allow the user to decide which monitor they wanted the crosshair to appear on.  For those with more extreme set-ups, eg users who constrain their UI to a portion of a monitor, they can also define the monitor space being used for the F10 map. 
I am completely new to Maven, so I had to change the pom.xml in order to get a package to appear.  I guess you have a different build process.  I have also tweaked the TheWay.lua to suppress duplicate network transmissions.
Please note that this PR includes a new dependency for apache.commons.cli.
If there are issues with my code (and I know of one at the moment relating to launch4j) then I will raise issues on my fork.

### CODE REVIEW

**Comment by aronCiucu** [comment]
Hello, good work there, when I get some more free time, I'd like to have a pass over the code (and perhaps other things too, since requests are piling up, but time is not)... Thanks

**Comment by BlueFinBima** [comment]
Hi Aron,  not a problem, and thanks for getting back to me so quickly.  Time is a precious commodity for everyone.  I've made a pre-release package on my fork for anyone who wants to kick the tyres.  If you have any questions once you get round to looking at the code, then let me know.

**Comment by BlueFinBima** [comment]
@aronCiucu Just wanted to let you know that I've now refactored the command line code, and the PR now includes the capability to load and save waypoint data #11.  I've added new fields to the Point object, but not implemented the use of them.

**Comment by BlueFinBima** [comment]
@aronCiucu I have now implemented enhanced Apache waypoint processing #27 , albeit in order to utilise this, you have to export the viewports, alter them, and then re-import these.  Obviously this is a little error prone, but it is do-able.  I think that I've probably done enough with DCSTheWay, at least for the time being.   
In this latest commit, I've made quite significant changes to the Apache and I have also added a sub-module to the repo. 
When you get around to reviewing this, I'm sure you'll have some questions so do not hesitate to contact me.

**Comment by BlueFinBima** [comment]
Hello @aronCiucu,  Just another update as it relates to this project.  I have made a Waypoint editor and made it public [here](https://github.com/BlueFinBima/DCS-The-Way-Changer).  I also created a Microsoft Installer project for it, and while it would have been simpler to add TheWay as a submodule to the editor, logically it needed to be the other way around.  The installer project wraps up TheWay and the Editor into one installable msi file.  It all got a little complicated because I was using VSCode for TheWay and VS2022 for the editor.  
Anyway, it all hangs together and works, but when you get round to reviewing the PR, we can discuss the right approach going forward.

**Comment by aronCiucu** [comment]
Hello, check out the new main branch which changes the codebase, see if multi monitor works as expected, if not, we'll see on that branch. The old java one is not maintained anymore

**Pull request closed without merging**
